.TH "data_index" 3 "Mon Nov 26 2012" "Version 1.0" "SneakyFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_index \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <index_block\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBindex_location\fP"
.br
.ti -1c
.RI "\fBlocations\fP \fBdata_locations\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBlocations\fP data_locations"

.SS "uint32_t index_location"


.SH "Author"
.PP 
Generated automatically by Doxygen for SneakyFS from the source code\&.
