.TH "sfstest.c" 3 "Mon Nov 26 2012" "Version 1.0" "SneakyFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sfstest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'glob_data\&.h'\fP
.br
\fC#include 'mount\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBcommand_buffer\fP [\fBMAX_INPUT_LENGTH\fP+1] = {NULL}"
.br
.ti -1c
.RI "char \fBio_buffer\fP [\fBMAX_IO_LENGTH\fP+1] = {NULL}"
.br
.ti -1c
.RI "char \fBdata_buffer_1\fP [\fBMAX_INPUT_LENGTH\fP] = {NULL}"
.br
.ti -1c
.RI "int \fBp1\fP"
.br
.ti -1c
.RI "int \fBp2\fP"
.br
.ti -1c
.RI "int \fBp3\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main ()"

.SH "Variable Documentation"
.PP 
.SS "char command_buffer[\fBMAX_INPUT_LENGTH\fP+1] = {NULL}"

.SS "char data_buffer_1[\fBMAX_INPUT_LENGTH\fP] = {NULL}"

.SS "char io_buffer[\fBMAX_IO_LENGTH\fP+1] = {NULL}"

.SS "int p1"

.SS "int p2"

.SS "int p3"

.SH "Author"
.PP 
Generated automatically by Doxygen for SneakyFS from the source code\&.
